version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: capstonex
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ml-service:
    build: 
      context: ./ml-service
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/capstonex
    depends_on:
      - db
    volumes:
      - ./ml-service:/app

volumes:
  pgdata:
