export const theme = {
  colors: {
    brand: {
      maroon: '#8B0000',
      navy: '#1C3D58',
      gold: '#F5C518',
      teal: '#0B9E8A',
    },
    background: '#EFEFEF',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#2B2B2B',
    primary: '#8B0000',
    primaryForeground: '#FFFFFF',
    secondary: '#1C3D58',
    secondaryForeground: '#FFFFFF',
    muted: '#DCDCDC',
    mutedForeground: '#555555',
    accent: '#F5C518',
    accentForeground: '#1A1A1A',
    destructive: '#DC3545',
    destructiveForeground: '#FFFFFF',
    border: '#DCDCDC',
    input: '#DCDCDC',
    success: '#28A745',
    warning: '#FD7E14',
    info: '#007BFF',
    error: '#DC3545',
  },
  spacing: {
    1: 4,
    2: 8,
    3: 12,
    4: 16,
    5: 20,
    6: 24,
    8: 32,
    10: 40,
    12: 48,
    16: 64,
  },
  radius: {
    sm: 6,
    md: 8,
    lg: 12,
    xl: 16,
    '2xl': 24,
    full: 9999,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 3,
    },
    card: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.05,
      shadowRadius: 20,
      elevation: 5,
    },
  },
};
